Import Required Libraries

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

Read Data From different formats

In [ ]:
df = pd.read_csv("usa_housing_kaggle.csv")
df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
0,221958,1,1.9,4827,1979,2,1.45,82240,48.60,5
1,771155,2,2.0,1035,1987,2,1.75,74315,92.03,9
2,231932,1,3.0,2769,1982,1,1.46,79249,52.08,3
3,465838,3,3.3,2708,1907,3,1.62,80587,61.65,1
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4

Find Shape of Data

In [ ]:
df.shape

(300, 10)

Find Missing Values

In [ ]:
df.isna().sum()

Price           0
Bedrooms        0
Bathrooms       0
SquareFeet      0
YearBuilt       0
GarageSpaces    0
LotSize         0
ZipCode         0
CrimeRate       0
SchoolRating    0
dtype: int64

Find data type of each column

In [ ]:
df.dtypes

Price             int64
Bedrooms          int64
Bathrooms       float64
SquareFeet        int64
YearBuilt         int64
GarageSpaces      int64
LotSize         float64
ZipCode           int64
CrimeRate       float64
SchoolRating      int64
dtype: object

Finding out Zero's

In [ ]:
(df==0).sum()

Price            0
Bedrooms         0
Bathrooms        0
SquareFeet       0
YearBuilt        0
GarageSpaces    72
LotSize          0
ZipCode          0
CrimeRate        0
SchoolRating     0
dtype: int64

Indexing and selecting data, sort data,

In [ ]:
df['Price'].head()

0    221958
1    771155
2    231932
3    465838
4    359178
Name: Price, dtype: int64

In [ ]:
df.columns

Index(['Price', 'Bedrooms', 'Bathrooms', 'SquareFeet', 'YearBuilt',
       'GarageSpaces', 'LotSize', 'ZipCode', 'CrimeRate', 'SchoolRating'],
      dtype='object')

Describe attributes of data

In [ ]:
df.describe()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
count,300.000000,300.000000,300.000000,300.00000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,522761.916667,2.966667,2.464000,3052.75000,1962.616667,1.513333,1.062200,54324.770000,49.324033,5.096667
std,256922.348275,1.451175,0.886184,1194.97144,36.005431,1.116832,0.543896,24718.938552,28.833220,2.674165
min,112666.000000,1.000000,1.000000,840.00000,1902.000000,0.000000,0.110000,10163.000000,0.190000,1.000000
25%,299936.500000,2.000000,1.700000,2053.50000,1931.750000,1.000000,0.570000,34175.000000,22.547500,3.000000
50%,505806.500000,3.000000,2.400000,3127.00000,1961.000000,1.000000,1.085000,54896.500000,49.970000,5.000000
75%,744603.750000,4.000000,3.200000,4081.00000,1994.000000,3.000000,1.482500,74108.000000,74.402500,8.000000
max,999684.000000,5.000000,4.000000,4997.00000,2022.000000,3.000000,2.000000,99881.000000,99.710000,9.000000

Counting unique values of data

In [ ]:
df.nunique()

Price           300
Bedrooms          5
Bathrooms        31
SquareFeet      285
YearBuilt       111
GarageSpaces      4
LotSize         154
ZipCode         300
CrimeRate       295
SchoolRating      9
dtype: int64

Read Dataframe

In [ ]:
d=pd.DataFrame({
    'ID':[101, 102, 103 ,104, 105],
    'NAME': ['Prajakta', 'Rutika', 'Srushti' ,'Pooja', 'Bhoomi'],
    'AGE': [19, 19, 19, 19, 19],
    'GENDER':['Female', 'Female', 'Female', 'Female', 'Female'],
    'DEPT': ['CSE-AI', 'IT' ,'IT' ,'IT' ,'CSE-AI'],
    'MARKS': [93 ,92 ,90, 91, 92],
    'ATTENDANCE': [95 ,92, 91, 95 ,95],
    'INTERSHIP': ['Yes' ,'Yes' ,'Yes' ,'NO' ,'Yes']
})

In [ ]:
print(d)

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

     Viewing Data

In [ ]:
d.head()

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d.tail(3)

    ID     NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
2  103  Srushti   19  Female      IT     90          91       Yes
3  104    Pooja   19  Female      IT     91          95        NO
4  105   Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
d.columns

Index(['ID', 'NAME', 'AGE', 'GENDER', 'DEPT', 'MARKS', 'ATTENDANCE',
       'INTERSHIP'],
      dtype='object')

In [ ]:
d.to_numpy()

array([[101, 'Prajakta', 19, 'Female', 'CSE-AI', 93, 95, 'Yes'],
       [102, 'Rutika', 19, 'Female', 'IT', 92, 92, 'Yes'],
       [103, 'Srushti', 19, 'Female', 'IT', 90, 91, 'Yes'],
       [104, 'Pooja', 19, 'Female', 'IT', 91, 95, 'NO'],
       [105, 'Bhoomi', 19, 'Female', 'CSE-AI', 92, 95, 'Yes']],
      dtype=object)

In [ ]:
d.dtypes

ID             int64
NAME          object
AGE            int64
GENDER        object
DEPT          object
MARKS          int64
ATTENDANCE     int64
INTERSHIP     object
dtype: object

In [ ]:
d.describe()

               ID   AGE      MARKS  ATTENDANCE
count    5.000000   5.0   5.000000    5.000000
mean   103.000000  19.0  91.600000   93.600000
std      1.581139   0.0   1.140175    1.949359
min    101.000000  19.0  90.000000   91.000000
25%    102.000000  19.0  91.000000   92.000000
50%    103.000000  19.0  92.000000   95.000000
75%    104.000000  19.0  92.000000   95.000000
max    105.000000  19.0  93.000000   95.000000

In [ ]:
d.sort_index(axis=1, ascending=False)

       NAME  MARKS INTERSHIP   ID  GENDER    DEPT  ATTENDANCE  AGE
0  Prajakta     93       Yes  101  Female  CSE-AI          95   19
1    Rutika     92       Yes  102  Female      IT          92   19
2   Srushti     90       Yes  103  Female      IT          91   19
3     Pooja     91        NO  104  Female      IT          95   19
4    Bhoomi     92       Yes  105  Female  CSE-AI          95   19

In [ ]:
d.sort_values(by="MARKS", ascending=False)

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes
3  104     Pooja   19  Female      IT     91          95        NO
2  103   Srushti   19  Female      IT     90          91       Yes

Selection

  Getitem[]

In [ ]:
d["MARKS"]

0    93
1    92
2    90
3    91
4    92
Name: MARKS, dtype: int64

In [ ]:
d[["NAME", "MARKS"]]

       NAME  MARKS
0  Prajakta     93
1    Rutika     92
2   Srushti     90
3     Pooja     91
4    Bhoomi     92

In [ ]:
d[0:3]

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes

      Selection by Lable

In [ ]:
d.loc[:, ["NAME", "MARKS"]]

       NAME  MARKS
0  Prajakta     93
1    Rutika     92
2   Srushti     90
3     Pooja     91
4    Bhoomi     92

In [ ]:
d.loc[0, "NAME"]

'Prajakta'

In [ ]:
d.at[0, "MARKS"]

np.int64(93)

Selection by position -- iloc[]

In [ ]:
d.iloc[3]

ID               104
NAME           Pooja
AGE               19
GENDER        Female
DEPT              IT
MARKS             91
ATTENDANCE        95
INTERSHIP         NO
Name: 3, dtype: object

In [ ]:
d.iloc[1:4, 0:3]

    ID     NAME  AGE
1  102   Rutika   19
2  103  Srushti   19
3  104    Pooja   19

In [ ]:
d.iloc[[0,2,4],[1,5]]

       NAME  MARKS
0  Prajakta     93
2   Srushti     90
4    Bhoomi     92

Boolean Indexing

In [ ]:
d[d["MARKS"]>91]

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d[d["DEPT"].isin(["CSE-AI"])]

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

Setting Values

In [ ]:
d.at[0,"MARKS"]=95

In [ ]:
d

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     95          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d.iat[1, 6] = 96

In [ ]:
d

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     95          95       Yes
1  102    Rutika   19  Female      IT     92          96       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
s1=pd.Series([1,2,3,4,5])
d["GRADE"]=s1

In [ ]:
d

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP  GRADE
0  101  Prajakta   19  Female  CSE-AI     95          95       Yes      1
1  102    Rutika   19  Female      IT     92          96       Yes      2
2  103   Srushti   19  Female      IT     90          91       Yes      3
3  104     Pooja   19  Female      IT     91          95        NO      4
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes      5

Operations
Stats(Mean)

In [ ]:
d.mean(numeric_only=True)

ID            103.0
AGE            19.0
MARKS          91.6
ATTENDANCE     93.6
dtype: float64

In [ ]:
d["MARKS"].mean()

np.float64(91.6)

 User defined functions

In [ ]:
d[["MARKS", "ATTENDANCE"]].agg(lambda x: x.mean() * 2)

MARKS         183.2
ATTENDANCE    187.2
dtype: float64

In [ ]:
d["MARKS"].transform(lambda x: x + 5)

0    98
1    97
2    95
3    96
4    97
Name: MARKS, dtype: int64

Value Counts

In [ ]:
d["DEPT"].value_counts()

DEPT
IT        3
CSE-AI    2
Name: count, dtype: int64

String Methods

In [ ]:
d["NAME"].str.lower()

0    prajakta
1      rutika
2     srushti
3       pooja
4      bhoomi
Name: NAME, dtype: object

Merge  
Concat

In [ ]:
result = pd.DataFrame({'RESULT':['Pass','Pass','Pass','Pass','Pass']})

In [ ]:
pd.concat([d, result], axis=1)

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP RESULT
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes   Pass
1  102    Rutika   19  Female      IT     92          92       Yes   Pass
2  103   Srushti   19  Female      IT     90          91       Yes   Pass
3  104     Pooja   19  Female      IT     91          95        NO   Pass
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes   Pass

Join

In [ ]:
dept = pd.DataFrame({
    'DEPT':['CSE-AI','IT'],
    'HOD':['Dr. Sharma','Dr. Patil']
})

In [ ]:
pd.merge(d, dept, on='DEPT')

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP         HOD
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes  Dr. Sharma
1  102    Rutika   19  Female      IT     92          92       Yes   Dr. Patil
2  103   Srushti   19  Female      IT     90          91       Yes   Dr. Patil
3  104     Pooja   19  Female      IT     91          95        NO   Dr. Patil
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes  Dr. Sharma

In [ ]:
d.sort_values(by='ATTENDANCE', ascending=True)

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
2  103   Srushti   19  Female      IT     90          91       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d.isnull()

      ID   NAME    AGE  GENDER   DEPT  MARKS  ATTENDANCE  INTERSHIP
0  False  False  False   False  False  False       False      False
1  False  False  False   False  False  False       False      False
2  False  False  False   False  False  False       False      False
3  False  False  False   False  False  False       False      False
4  False  False  False   False  False  False       False      False

In [ ]:
d.isna()

      ID   NAME    AGE  GENDER   DEPT  MARKS  ATTENDANCE  INTERSHIP
0  False  False  False   False  False  False       False      False
1  False  False  False   False  False  False       False      False
2  False  False  False   False  False  False       False      False
3  False  False  False   False  False  False       False      False
4  False  False  False   False  False  False       False      False

In [ ]:
d.notna()

     ID  NAME   AGE  GENDER  DEPT  MARKS  ATTENDANCE  INTERSHIP
0  True  True  True    True  True   True        True       True
1  True  True  True    True  True   True        True       True
2  True  True  True    True  True   True        True       True
3  True  True  True    True  True   True        True       True
4  True  True  True    True  True   True        True       True

In [ ]:
d.dropna()

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d.fillna(value=5)

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d.interpolate()

/tmp/ipython-input-3264332000.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  d.interpolate()

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d.loc[len(d)] = [102, 'Rutika', 19, 'Female', 'IT', 92, 92, 'Yes']

In [ ]:
d

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes
5  102    Rutika   19  Female      IT     92          92       Yes

In [ ]:
d.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [ ]:
d.drop_duplicates()

    ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes

In [ ]:
d['AGE']=d['AGE'].astype(float)

In [ ]:
print(d.dtypes)

ID              int64
NAME           object
AGE           float64
GENDER         object
DEPT           object
MARKS           int64
ATTENDANCE      int64
INTERSHIP      object
dtype: object

In [ ]:
d.convert_dtypes

<bound method NDFrame.convert_dtypes of     ID      NAME   AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta  19.0  Female  CSE-AI     93          95       Yes
1  102    Rutika  19.0  Female      IT     92          92       Yes
2  103   Srushti  19.0  Female      IT     90          91       Yes
3  104     Pooja  19.0  Female      IT     91          95        NO
4  105    Bhoomi  19.0  Female  CSE-AI     92          95       Yes
5  102    Rutika  19.0  Female      IT     92          92       Yes>

In [ ]:
d

    ID      NAME   AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta  19.0  Female  CSE-AI     93          95       Yes
1  102    Rutika  19.0  Female      IT     92          92       Yes
2  103   Srushti  19.0  Female      IT     90          91       Yes
3  104     Pooja  19.0  Female      IT     91          95        NO
4  105    Bhoomi  19.0  Female  CSE-AI     92          95       Yes
5  102    Rutika  19.0  Female      IT     92          92       Yes

In [ ]:
d.shape

(5, 8)

In [ ]:
(d==0).sum()

ID            0
NAME          0
AGE           0
GENDER        0
DEPT          0
MARKS         0
ATTENDANCE    0
INTERSHIP     0
dtype: int64

In [ ]:
d.info

<bound method DataFrame.info of     ID      NAME  AGE  GENDER    DEPT  MARKS  ATTENDANCE INTERSHIP
0  101  Prajakta   19  Female  CSE-AI     93          95       Yes
1  102    Rutika   19  Female      IT     92          92       Yes
2  103   Srushti   19  Female      IT     90          91       Yes
3  104     Pooja   19  Female      IT     91          95        NO
4  105    Bhoomi   19  Female  CSE-AI     92          95       Yes>

In [ ]:
d['DEPT'].nunique()

2